import Head from 'next/head'
import Header from '../components/header';
import Footer from '../components/footer';
import Breadcrumb from '../components/breadcrumb';
import Images from '../components/images';
export default function header () {

  return (
    <div>
       <Head>
    
        <title>Charles Cantin - Photographe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header /><div className='relative'>
       </div>
        <Breadcrumb/>
        <Images/>
    <Footer />
    </div>
  );
};