import Head from 'next/head'
import Header from '../components/header';
import Footer from '../components/footer';

export default function header () {

  return (
    <div>
       <Head>
    
        <title>Charles Cantin - Photographe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <Header /><div className='relative'>
        <img className='h-[calc(100vh-148px)] object-cover w-screen' src="https://zupimages.net/up/21/50/sqyn.jpg" alt="" />
        <h1 className="absolute inset-0 z-10 flex justify-center items-center text-6xl text-white">CHARLES CANTIN - PHOTOGRAPHE</h1> 
    </div>

    <Footer />
    </div>
  );
};