import Head from 'next/head'
import Header from '../components/header';
import Footer from '../components/footer';
import { fetchAPI } from '../lib/api';


export default function header ({accueil}) {

  return (
    <div>
       <Head>
    
        <title>Charles Cantin - Photographe</title>
        <meta name="description" content="Generated by myself" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <Header /><div className='relative'>
        <img className='h-[calc(100vh-148px)] object-cover w-screen' src={accueil.Image.url} alt="Image-cover" />
        <h1 className="absolute inset-0 z-10 flex justify-center items-center text-6xl text-white">{accueil.Titre}</h1> 
    </div>

    <Footer />
    </div>
  );
};
export async function getStaticProps() {

  const [accueil] = await Promise.all([
    fetchAPI("/accueil"),

  ]);
  return{
    props: {accueil},
  };
}